#! /bin/sh

# run the xrandr command if an external monitor is connected to the
# laptop.  This must be executed before the polybar command, so that
# polybar can set the two separate bars properly.
if [ -x $HOME/.config/bspwm/bspwm_dual_monitor ];then
  bspwm_dual_monitor
  bspc monitor eDP -d 1 2 3 4 5
  bspc monitor HDMI-A-0 -d 6 7 8 9 0
  feh --bg-fill --randomize $HOME/GitRepos/wallpapers/* --bg-fill --randomize $HOME/GitRepos/wallpapers/*&
else 
  bspc monitor -d 1 2 3 4 5 6 7 8 9 0
  feh --bg-fill --randomize $HOME/GitRepos/wallpapers/*&
fi

pgrep -x sxhkd > /dev/null || sxhkd &


$HOME/.config/polybar/launch.sh &
picom &

bspc config border_width         2
bspc config window_gap           10

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true
bspc config top_padding 30
bspc config right_padding 0
bspc config bottom_padding 0
bspc config left_padding 0

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^6'
bspc rule -a Firefox desktop='^6'
bspc rule -a mplayer2 state=floating
bspc rule -a Spotify desktop='^5'

xsetroot -cursor_name left_ptr &
